### PR TITLE
Add license boilerplates of the Apache License 2.0

### PR DESCRIPTION
**Pull request by dmikurube**
Adding explicit license boilerplates.

### CODE REVIEW

**Review by vietnguyen-td — APPROVED** [review]
LGTM

**Review by nukala — APPROVED** [review]
Consider incrementing version, 
otherwise LGTM

**Comment by dmikurube** [comment]
Already incremented to `0.3.0-SNAPSHOT` at #17, and 0.3.0 has not been released yet.

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
